### ISSUE TITLE
Crushed when user click pickerBtn on left bottom corner on DatePicker 

### ISSUE THREAD

**Issue by lexy1105** [Mommoo/MaterialCalendar#1]
How are you?
I'm gonna use your datepicker on my app
But when i test your app, i got crush
There is pickerBtn on left bottom corner of datepicker dialog
Please check yourself why it crsuhed
Please check screenshot, too
http://prntscr.com/jkxgbj
Thanks

**Comment by lexy1105** [comment]
http://prntscr.com/jkxgsl

**Comment by Mommoo** [comment]
@yang511 okay i will check about what you told me.

**Comment by Mommoo** [comment]
@yang511 i push up bug fix version.. 
i will close this issue
